name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mysql, zip
    
    - name: Validate composer.json
      run: composer validate --strict
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Deploy to Hostinger
      run: |
        # Install lftp
        sudo apt-get update
        sudo apt-get install -y lftp
        
        # Deploy using lftp
        lftp -c "
          set ssl:verify-certificate no;
          open ftp://${{ secrets.HOSTINGER_USER }}:${{ secrets.HOSTINGER_PASSWORD }}@${{ secrets.HOSTINGER_HOST }};
          mirror -R --exclude-glob .git* --exclude-glob .github* --exclude-glob node_modules* --exclude-glob vendor* --exclude-glob tests* --exclude-glob .env* --exclude-glob .gitignore --exclude-glob README.md ./ ${{ secrets.HOSTINGER_PATH }};
          quit;
        " 