name: Simple Sync Deployment

on:
  push:
    branches: [ main ] # Deploy only when pushing to main
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    name: Sync Files to Server
    # Run only on push to main or manual dispatch
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      # 1. Get the latest code from the repository
      # This represents the code you worked on locally and pushed
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup SSH connection capability to the server
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # MUST be configured in GitHub secrets

      # 3. Sync YOUR application files to the server using Rsync
      # This copies files from the runner's checkout dir to the server.
      - name: Sync Application Files to Hostinger
        env:
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          HOSTINGER_PATH: ${{ secrets.HOSTINGER_PATH }} # e.g., public_html/myapp
          SSH_PORT: 65002 # Hostinger's non-standard SSH port
        run: |
          echo "🚀 Syncing YOUR application files to the server..."
          # Use StrictHostKeyChecking=no for simplicity. Manage known_hosts for better security if preferred.
          SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

          # --- Define files/directories to EXCLUDE from sync ---
          # We EXCLUDE dependencies, git files, and environment config.
          # We assume 'vendor' and 'node_modules' already exist correctly on the server.
          EXCLUDES=(
            --exclude='.git'                # Exclude Git repository files
            --exclude='.github'             # Exclude GitHub Actions workflow files
            --exclude='vendor/'             # Exclude PHP dependencies folder
            --exclude='node_modules/'       # Exclude Node.js dependencies folder
            --exclude='.env'                # Exclude environment file (MUST be managed on server)
            --exclude='.env.example'        # Exclude example environment file
            --exclude='.gitignore'          # Exclude git ignore rules file
            # Exclude common framework storage/cache directories - prevents overwriting server sessions/cache
            --exclude='/storage/framework/cache/' # Adjust paths if your framework uses different ones
            --exclude='/storage/framework/sessions/'
            --exclude='/storage/framework/views/'
            --exclude='/storage/logs/'
            --exclude='bootstrap/cache/'    # Another common cache location (Laravel)
            # --- Add any other files/folders YOU DON'T want copied from your repo ---
            # e.g., local development tools, documentation you don't need on the server
            --exclude='README.md'
            --exclude='phpunit.xml'
            # Optional: You might even exclude composer/package files if they never change
            # and you *really* don't want them synced.
            # --exclude='composer.json'
            # --exclude='composer.lock'
            # --exclude='package.json'
            # --exclude='package-lock.json'
          )

          # The destination path on the remote server
          # Ensure the trailing slash on HOSTINGER_PATH if needed, or add one here.
          REMOTE_TARGET="${HOSTINGER_USER}@${HOSTINGER_HOST}:${HOSTINGER_PATH}/"

          # --- Perform the sync ---
          # -a = archive mode (preserves permissions, ownership, timestamps, etc.)
          # -v = verbose (shows files being transferred)
          # -z = compress file data during the transfer
          # NO --delete flag = only adds new files or updates existing ones on the server. It will NOT remove files.
          rsync -avz -e "ssh -p ${SSH_PORT} ${SSH_OPTIONS}" "${EXCLUDES[@]}" ./ "${REMOTE_TARGET}"

          echo "✅ Application file sync completed."
          echo "✅ NOTE: This job ONLY copied your source files."
          echo "   - It did NOT install dependencies (vendor/node_modules)."
          echo "   - It did NOT run cache clearing, migrations, or other server commands."