name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mysql, zip
    
    - name: Validate composer.json
      run: composer validate --strict
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Deploy to Hostinger
      run: |
        # Remove PHP PPA if it exists
        sudo rm -f /etc/apt/sources.list.d/ondrej-*.list
        
        # Update package lists and install required packages
        sudo apt-get update
        sudo apt-get install -y rsync
        
        # Create SSH config file
        mkdir -p ~/.ssh
        echo "Host ${{ secrets.HOSTINGER_HOST }}
          HostName ${{ secrets.HOSTINGER_HOST }}
          Port 65002
          User ${{ secrets.HOSTINGER_USER }}
          IdentityFile ~/.ssh/deploy_key
          StrictHostKeyChecking no" > ~/.ssh/config
        
        # Create SSH key file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        chmod 600 ~/.ssh/config
        
        # Deploy using SSH key
        rsync -avz -e "ssh -p 65002" --exclude '.git' --exclude '.github' --exclude 'vendor' --exclude 'node_modules' --exclude '.env' --exclude '.gitignore' --exclude 'README.md' ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_PATH }} 