name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mysql, zip
    
    - name: Validate composer.json
      run: composer validate --strict
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Deploy to Hostinger
      run: |
        # Update package lists and install required packages
        sudo apt-get update
        sudo apt-get install -y sshpass rsync
        
        # Create SSH config file
        mkdir -p ~/.ssh
        echo "Host ${{ secrets.HOSTINGER_HOST }}
          HostName ${{ secrets.HOSTINGER_HOST }}
          User ${{ secrets.HOSTINGER_USER }}
          StrictHostKeyChecking no" > ~/.ssh/config
        
        # Set proper permissions for SSH config
        chmod 600 ~/.ssh/config
        
        # Deploy using SSH with password
        sshpass -p "${{ secrets.HOSTINGER_PASSWORD }}" rsync -avz --exclude '.git' --exclude '.github' --exclude 'vendor' --exclude 'node_modules' --exclude '.env' --exclude '.gitignore' --exclude 'README.md' ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_PATH }} 